name: craw
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]  
    steps:
    - name: set up environment variable
      run: |
        PGHOST = { secrets.PGHOST }
        PGUSER = { secret.PGUSER }
        PGDATABASE = { secret.PGDATABASE }
        PGPASSWORD = { secret.PGPASSWORD }
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run
      run: |
        npm run dev
        npm run dml
